deploy:
  needs: build
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull sarathchandran0707/densmile-website:latest
          docker stop densmile-container || true
          docker rm densmile-container || true
          docker run -d --name densmile-container -p 80:80 sarathchandran0707/densmile-website:latest

    - name: Rollback on Failure
      if: failure()
      run: |
        chmod +x rollback.sh
        ./rollback.sh
